version: 2.1

executors:
  mac:
    macos:
      xcode: "10.1.0"
    environment:
      TERM: "xterm"
  win:
    # copied the parameters from
    # https://circleci.com/developer/orbs/orb/circleci/windows
    machine:
      image: "windows-server-2019-vs2019:stable"
      resource_class: "windows.medium"
      shell: "bash.exe"

jobs:
  # installs Chromium through Puppeteer package
  windows-test:
    working_directory: ~/app
    executor: win
    steps:
      - checkout
      - run: npm ci
      - run: npm run cy:verify
      - run: npm run cy:info
      - run: npm test

  # installs Chrome using Chocolatey
  # https://chocolatey.org/packages/GoogleChrome
  windows-chocolatey-test:
    working_directory: ~/app
    executor: win
    steps:
      - checkout
      - run:
          name: install
          command: npm ci
          environment:
            PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      - run:
      - run: npm run cy:verify
      - run: npm run cy:info
      - run: npx cypress run --browser chrome --headless

workflows:
  win-build:
    jobs:
      - windows-test
      - windows-chocolatey-test
